###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue May 26 19:54:41 2026

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       mig_7series_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K480T-FFG1156
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         533.33000000000004 MHz
##                    Time Period:       1875 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->UDIMMs->MT8KTF51264AZ-1G4
## Data Width: 64
## Time Period: 1875
## Data Mask: 1
#####################################################################################################################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################



##################################################################################################
## Controller 1
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 8
## Time Period: 1875
## Data Mask: 1
##################################################################################################