##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue May 26 19:54:41 2026

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       mig_7series_0.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K480T-FFG1156
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         533.33000000000004 MHz
##                    Time Period:       1875 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->UDIMMs->MT8KTF51264AZ-1G4
## Data Width: 64
## Time Period: 1875
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr3_ck_p[*]} ]
          
create_clock -period 1.875 [get_ports c0_sys_clk_p]
          
create_clock -period 5 [get_ports clk_ref_p]
          
############## NET - IOSTANDARD ##################


# PadFunction: IO_L1N_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[0]}]
set_property PACKAGE_PIN C25 [get_ports {c0_ddr3_dq[0]}]

# PadFunction: IO_L2P_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[1]}]
set_property PACKAGE_PIN A24 [get_ports {c0_ddr3_dq[1]}]

# PadFunction: IO_L2N_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[2]}]
set_property PACKAGE_PIN A25 [get_ports {c0_ddr3_dq[2]}]

# PadFunction: IO_L4P_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[3]}]
set_property PACKAGE_PIN B26 [get_ports {c0_ddr3_dq[3]}]

# PadFunction: IO_L4N_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[4]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[4]}]
set_property PACKAGE_PIN B27 [get_ports {c0_ddr3_dq[4]}]

# PadFunction: IO_L5P_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[5]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[5]}]
set_property PACKAGE_PIN B28 [get_ports {c0_ddr3_dq[5]}]

# PadFunction: IO_L5N_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[6]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[6]}]
set_property PACKAGE_PIN A28 [get_ports {c0_ddr3_dq[6]}]

# PadFunction: IO_L6P_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[7]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[7]}]
set_property PACKAGE_PIN C27 [get_ports {c0_ddr3_dq[7]}]

# PadFunction: IO_L7N_T1_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[8]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[8]}]
set_property PACKAGE_PIN E24 [get_ports {c0_ddr3_dq[8]}]

# PadFunction: IO_L8P_T1_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[9]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[9]}]
set_property PACKAGE_PIN D26 [get_ports {c0_ddr3_dq[9]}]

# PadFunction: IO_L8N_T1_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[10]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[10]}]
set_property PACKAGE_PIN D27 [get_ports {c0_ddr3_dq[10]}]

# PadFunction: IO_L10P_T1_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[11]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[11]}]
set_property PACKAGE_PIN F28 [get_ports {c0_ddr3_dq[11]}]

# PadFunction: IO_L10N_T1_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[12]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[12]}]
set_property PACKAGE_PIN E28 [get_ports {c0_ddr3_dq[12]}]

# PadFunction: IO_L11P_T1_SRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[13]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[13]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[13]}]
set_property PACKAGE_PIN F25 [get_ports {c0_ddr3_dq[13]}]

# PadFunction: IO_L11N_T1_SRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[14]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[14]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[14]}]
set_property PACKAGE_PIN F26 [get_ports {c0_ddr3_dq[14]}]

# PadFunction: IO_L12P_T1_MRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[15]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[15]}]
set_property PACKAGE_PIN E26 [get_ports {c0_ddr3_dq[15]}]

# PadFunction: IO_L13P_T2_MRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[16]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[16]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[16]}]
set_property PACKAGE_PIN H27 [get_ports {c0_ddr3_dq[16]}]

# PadFunction: IO_L13N_T2_MRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[17]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[17]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[17]}]
set_property PACKAGE_PIN G27 [get_ports {c0_ddr3_dq[17]}]

# PadFunction: IO_L14P_T2_SRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[18]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[18]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[18]}]
set_property PACKAGE_PIN G25 [get_ports {c0_ddr3_dq[18]}]

# PadFunction: IO_L14N_T2_SRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[19]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[19]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[19]}]
set_property PACKAGE_PIN G26 [get_ports {c0_ddr3_dq[19]}]

# PadFunction: IO_L16N_T2_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[20]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[20]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[20]}]
set_property PACKAGE_PIN H25 [get_ports {c0_ddr3_dq[20]}]

# PadFunction: IO_L17P_T2_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[21]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[21]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[21]}]
set_property PACKAGE_PIN H28 [get_ports {c0_ddr3_dq[21]}]

# PadFunction: IO_L17N_T2_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[22]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[22]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[22]}]
set_property PACKAGE_PIN G28 [get_ports {c0_ddr3_dq[22]}]

# PadFunction: IO_L18P_T2_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[23]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[23]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[23]}]
set_property PACKAGE_PIN J26 [get_ports {c0_ddr3_dq[23]}]

# PadFunction: IO_L20P_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[24]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[24]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[24]}]
set_property PACKAGE_PIN L24 [get_ports {c0_ddr3_dq[24]}]

# PadFunction: IO_L20N_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[25]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[25]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[25]}]
set_property PACKAGE_PIN K24 [get_ports {c0_ddr3_dq[25]}]

# PadFunction: IO_L22P_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[26]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[26]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[26]}]
set_property PACKAGE_PIN K26 [get_ports {c0_ddr3_dq[26]}]

# PadFunction: IO_L22N_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[27]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[27]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[27]}]
set_property PACKAGE_PIN K27 [get_ports {c0_ddr3_dq[27]}]

# PadFunction: IO_L23P_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[28]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[28]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[28]}]
set_property PACKAGE_PIN M26 [get_ports {c0_ddr3_dq[28]}]

# PadFunction: IO_L23N_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[29]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[29]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[29]}]
set_property PACKAGE_PIN M27 [get_ports {c0_ddr3_dq[29]}]

# PadFunction: IO_L24P_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[30]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[30]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[30]}]
set_property PACKAGE_PIN L28 [get_ports {c0_ddr3_dq[30]}]

# PadFunction: IO_L24N_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dq[31]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[31]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[31]}]
set_property PACKAGE_PIN L29 [get_ports {c0_ddr3_dq[31]}]

# PadFunction: IO_L1N_T0_AD0N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[32]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[32]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[32]}]
set_property PACKAGE_PIN M28 [get_ports {c0_ddr3_dq[32]}]

# PadFunction: IO_L2P_T0_AD8P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[33]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[33]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[33]}]
set_property PACKAGE_PIN P29 [get_ports {c0_ddr3_dq[33]}]

# PadFunction: IO_L2N_T0_AD8N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[34]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[34]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[34]}]
set_property PACKAGE_PIN N29 [get_ports {c0_ddr3_dq[34]}]

# PadFunction: IO_L4P_T0_AD9P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[35]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[35]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[35]}]
set_property PACKAGE_PIN N24 [get_ports {c0_ddr3_dq[35]}]

# PadFunction: IO_L4N_T0_AD9N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[36]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[36]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[36]}]
set_property PACKAGE_PIN N25 [get_ports {c0_ddr3_dq[36]}]

# PadFunction: IO_L5P_T0_AD2P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[37]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[37]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[37]}]
set_property PACKAGE_PIN P25 [get_ports {c0_ddr3_dq[37]}]

# PadFunction: IO_L5N_T0_AD2N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[38]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[38]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[38]}]
set_property PACKAGE_PIN P26 [get_ports {c0_ddr3_dq[38]}]

# PadFunction: IO_L6P_T0_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[39]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[39]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[39]}]
set_property PACKAGE_PIN R24 [get_ports {c0_ddr3_dq[39]}]

# PadFunction: IO_L7N_T1_AD10N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[40]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[40]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[40]}]
set_property PACKAGE_PIN R27 [get_ports {c0_ddr3_dq[40]}]

# PadFunction: IO_L8P_T1_AD3P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[41]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[41]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[41]}]
set_property PACKAGE_PIN T25 [get_ports {c0_ddr3_dq[41]}]

# PadFunction: IO_L8N_T1_AD3N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[42]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[42]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[42]}]
set_property PACKAGE_PIN T26 [get_ports {c0_ddr3_dq[42]}]

# PadFunction: IO_L10P_T1_AD4P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[43]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[43]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[43]}]
set_property PACKAGE_PIN U27 [get_ports {c0_ddr3_dq[43]}]

# PadFunction: IO_L10N_T1_AD4N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[44]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[44]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[44]}]
set_property PACKAGE_PIN U28 [get_ports {c0_ddr3_dq[44]}]

# PadFunction: IO_L11P_T1_SRCC_AD12P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[45]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[45]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[45]}]
set_property PACKAGE_PIN T28 [get_ports {c0_ddr3_dq[45]}]

# PadFunction: IO_L11N_T1_SRCC_AD12N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[46]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[46]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[46]}]
set_property PACKAGE_PIN T29 [get_ports {c0_ddr3_dq[46]}]

# PadFunction: IO_L12P_T1_MRCC_AD5P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[47]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[47]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[47]}]
set_property PACKAGE_PIN R28 [get_ports {c0_ddr3_dq[47]}]

# PadFunction: IO_L13P_T2_MRCC_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[48]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[48]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[48]}]
set_property PACKAGE_PIN R31 [get_ports {c0_ddr3_dq[48]}]

# PadFunction: IO_L13N_T2_MRCC_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[49]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[49]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[49]}]
set_property PACKAGE_PIN P31 [get_ports {c0_ddr3_dq[49]}]

# PadFunction: IO_L14P_T2_SRCC_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[50]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[50]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[50]}]
set_property PACKAGE_PIN P30 [get_ports {c0_ddr3_dq[50]}]

# PadFunction: IO_L14N_T2_SRCC_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[51]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[51]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[51]}]
set_property PACKAGE_PIN N30 [get_ports {c0_ddr3_dq[51]}]

# PadFunction: IO_L16N_T2_A27_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[52]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[52]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[52]}]
set_property PACKAGE_PIN M32 [get_ports {c0_ddr3_dq[52]}]

# PadFunction: IO_L17P_T2_A26_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[53]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[53]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[53]}]
set_property PACKAGE_PIN N33 [get_ports {c0_ddr3_dq[53]}]

# PadFunction: IO_L17N_T2_A25_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[54]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[54]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[54]}]
set_property PACKAGE_PIN M33 [get_ports {c0_ddr3_dq[54]}]

# PadFunction: IO_L18P_T2_A24_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[55]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[55]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[55]}]
set_property PACKAGE_PIN P34 [get_ports {c0_ddr3_dq[55]}]

# PadFunction: IO_L20P_T3_A20_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[56]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[56]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[56]}]
set_property PACKAGE_PIN T30 [get_ports {c0_ddr3_dq[56]}]

# PadFunction: IO_L20N_T3_A19_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[57]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[57]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[57]}]
set_property PACKAGE_PIN T31 [get_ports {c0_ddr3_dq[57]}]

# PadFunction: IO_L22P_T3_A17_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[58]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[58]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[58]}]
set_property PACKAGE_PIN R32 [get_ports {c0_ddr3_dq[58]}]

# PadFunction: IO_L22N_T3_A16_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[59]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[59]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[59]}]
set_property PACKAGE_PIN P32 [get_ports {c0_ddr3_dq[59]}]

# PadFunction: IO_L23P_T3_FOE_B_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[60]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[60]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[60]}]
set_property PACKAGE_PIN T33 [get_ports {c0_ddr3_dq[60]}]

# PadFunction: IO_L23N_T3_FWE_B_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[61]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[61]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[61]}]
set_property PACKAGE_PIN T34 [get_ports {c0_ddr3_dq[61]}]

# PadFunction: IO_L24P_T3_RS1_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[62]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[62]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[62]}]
set_property PACKAGE_PIN R33 [get_ports {c0_ddr3_dq[62]}]

# PadFunction: IO_L24N_T3_RS0_15 
set_property SLEW FAST [get_ports {c0_ddr3_dq[63]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dq[63]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dq[63]}]
set_property PACKAGE_PIN R34 [get_ports {c0_ddr3_dq[63]}]

# PadFunction: IO_L1P_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[15]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[15]}]
set_property PACKAGE_PIN A29 [get_ports {c0_ddr3_addr[15]}]

# PadFunction: IO_L1N_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[14]}]
set_property PACKAGE_PIN A30 [get_ports {c0_ddr3_addr[14]}]

# PadFunction: IO_L2P_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[13]}]
set_property PACKAGE_PIN B30 [get_ports {c0_ddr3_addr[13]}]

# PadFunction: IO_L2N_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[12]}]
set_property PACKAGE_PIN A31 [get_ports {c0_ddr3_addr[12]}]

# PadFunction: IO_L4P_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[11]}]
set_property PACKAGE_PIN B33 [get_ports {c0_ddr3_addr[11]}]

# PadFunction: IO_L4N_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[10]}]
set_property PACKAGE_PIN A33 [get_ports {c0_ddr3_addr[10]}]

# PadFunction: IO_L5P_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[9]}]
set_property PACKAGE_PIN C32 [get_ports {c0_ddr3_addr[9]}]

# PadFunction: IO_L5N_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[8]}]
set_property PACKAGE_PIN C33 [get_ports {c0_ddr3_addr[8]}]

# PadFunction: IO_L6P_T0_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[7]}]
set_property PACKAGE_PIN C29 [get_ports {c0_ddr3_addr[7]}]

# PadFunction: IO_L6N_T0_VREF_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[6]}]
set_property PACKAGE_PIN C30 [get_ports {c0_ddr3_addr[6]}]

# PadFunction: IO_L7P_T1_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[5]}]
set_property PACKAGE_PIN D29 [get_ports {c0_ddr3_addr[5]}]

# PadFunction: IO_L7N_T1_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[4]}]
set_property PACKAGE_PIN D30 [get_ports {c0_ddr3_addr[4]}]

# PadFunction: IO_L8P_T1_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[3]}]
set_property PACKAGE_PIN F34 [get_ports {c0_ddr3_addr[3]}]

# PadFunction: IO_L8N_T1_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[2]}]
set_property PACKAGE_PIN E34 [get_ports {c0_ddr3_addr[2]}]

# PadFunction: IO_L9P_T1_DQS_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[1]}]
set_property PACKAGE_PIN D34 [get_ports {c0_ddr3_addr[1]}]

# PadFunction: IO_L9N_T1_DQS_16 
set_property SLEW FAST [get_ports {c0_ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_addr[0]}]
set_property PACKAGE_PIN C34 [get_ports {c0_ddr3_addr[0]}]

# PadFunction: IO_L10P_T1_16 
set_property SLEW FAST [get_ports {c0_ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_ba[2]}]
set_property PACKAGE_PIN F33 [get_ports {c0_ddr3_ba[2]}]

# PadFunction: IO_L10N_T1_16 
set_property SLEW FAST [get_ports {c0_ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_ba[1]}]
set_property PACKAGE_PIN E33 [get_ports {c0_ddr3_ba[1]}]

# PadFunction: IO_L11P_T1_SRCC_16 
set_property SLEW FAST [get_ports {c0_ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_ba[0]}]
set_property PACKAGE_PIN E31 [get_ports {c0_ddr3_ba[0]}]

# PadFunction: IO_L11N_T1_SRCC_16 
set_property SLEW FAST [get_ports {c0_ddr3_ras_n}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_ras_n}]
set_property PACKAGE_PIN D31 [get_ports {c0_ddr3_ras_n}]

# PadFunction: IO_L12P_T1_MRCC_16 
set_property SLEW FAST [get_ports {c0_ddr3_cas_n}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_cas_n}]
set_property PACKAGE_PIN E32 [get_ports {c0_ddr3_cas_n}]

# PadFunction: IO_L12N_T1_MRCC_16 
set_property SLEW FAST [get_ports {c0_ddr3_we_n}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_we_n}]
set_property PACKAGE_PIN D32 [get_ports {c0_ddr3_we_n}]

# PadFunction: IO_L12N_T1_MRCC_17 
set_property SLEW FAST [get_ports {c0_ddr3_reset_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {c0_ddr3_reset_n}]
set_property PACKAGE_PIN E27 [get_ports {c0_ddr3_reset_n}]

# PadFunction: IO_L15N_T2_DQS_16 
set_property SLEW FAST [get_ports {c0_ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_cke[0]}]
set_property PACKAGE_PIN H30 [get_ports {c0_ddr3_cke[0]}]

# PadFunction: IO_L16P_T2_16 
set_property SLEW FAST [get_ports {c0_ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_odt[0]}]
set_property PACKAGE_PIN F29 [get_ports {c0_ddr3_odt[0]}]

# PadFunction: IO_L15P_T2_DQS_16 
set_property SLEW FAST [get_ports {c0_ddr3_cs_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_cs_n[0]}]
set_property PACKAGE_PIN H29 [get_ports {c0_ddr3_cs_n[0]}]

# PadFunction: IO_L1P_T0_17 
set_property SLEW FAST [get_ports {c0_ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[0]}]
set_property PACKAGE_PIN C24 [get_ports {c0_ddr3_dm[0]}]

# PadFunction: IO_L7P_T1_17 
set_property SLEW FAST [get_ports {c0_ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[1]}]
set_property PACKAGE_PIN F24 [get_ports {c0_ddr3_dm[1]}]

# PadFunction: IO_L16P_T2_17 
set_property SLEW FAST [get_ports {c0_ddr3_dm[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[2]}]
set_property PACKAGE_PIN H24 [get_ports {c0_ddr3_dm[2]}]

# PadFunction: IO_L19P_T3_17 
set_property SLEW FAST [get_ports {c0_ddr3_dm[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[3]}]
set_property PACKAGE_PIN L25 [get_ports {c0_ddr3_dm[3]}]

# PadFunction: IO_L1P_T0_AD0P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dm[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[4]}]
set_property PACKAGE_PIN N28 [get_ports {c0_ddr3_dm[4]}]

# PadFunction: IO_L7P_T1_AD10P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dm[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[5]}]
set_property PACKAGE_PIN R26 [get_ports {c0_ddr3_dm[5]}]

# PadFunction: IO_L16P_T2_A28_15 
set_property SLEW FAST [get_ports {c0_ddr3_dm[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[6]}]
set_property PACKAGE_PIN N32 [get_ports {c0_ddr3_dm[6]}]

# PadFunction: IO_L19P_T3_A22_15 
set_property SLEW FAST [get_ports {c0_ddr3_dm[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c0_ddr3_dm[7]}]
set_property PACKAGE_PIN U30 [get_ports {c0_ddr3_dm[7]}]

# PadFunction: IO_L13P_T2_MRCC_16 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_sys_clk_p}]
set_property PACKAGE_PIN G30 [get_ports {c0_sys_clk_p}]

# PadFunction: IO_L13N_T2_MRCC_16 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_sys_clk_n}]
set_property PACKAGE_PIN F30 [get_ports {c0_sys_clk_n}]

# PadFunction: IO_L14P_T2_SRCC_12 
set_property IOSTANDARD LVDS_25 [get_ports {clk_ref_p}]
set_property PACKAGE_PIN AH27 [get_ports {clk_ref_p}]

# PadFunction: IO_L14N_T2_SRCC_12 
set_property IOSTANDARD LVDS_25 [get_ports {clk_ref_n}]
set_property PACKAGE_PIN AH28 [get_ports {clk_ref_n}]

# PadFunction: IO_L3P_T0_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[0]}]
set_property PACKAGE_PIN B25 [get_ports {c0_ddr3_dqs_p[0]}]

# PadFunction: IO_L3N_T0_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[0]}]
set_property PACKAGE_PIN A26 [get_ports {c0_ddr3_dqs_n[0]}]

# PadFunction: IO_L9P_T1_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[1]}]
set_property PACKAGE_PIN D24 [get_ports {c0_ddr3_dqs_p[1]}]

# PadFunction: IO_L9N_T1_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[1]}]
set_property PACKAGE_PIN D25 [get_ports {c0_ddr3_dqs_n[1]}]

# PadFunction: IO_L15P_T2_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[2]}]
set_property PACKAGE_PIN J24 [get_ports {c0_ddr3_dqs_p[2]}]

# PadFunction: IO_L15N_T2_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[2]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[2]}]
set_property PACKAGE_PIN J25 [get_ports {c0_ddr3_dqs_n[2]}]

# PadFunction: IO_L21P_T3_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[3]}]
set_property PACKAGE_PIN K28 [get_ports {c0_ddr3_dqs_p[3]}]

# PadFunction: IO_L21N_T3_DQS_17 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[3]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[3]}]
set_property PACKAGE_PIN K29 [get_ports {c0_ddr3_dqs_n[3]}]

# PadFunction: IO_L3P_T0_DQS_AD1P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[4]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[4]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[4]}]
set_property PACKAGE_PIN P27 [get_ports {c0_ddr3_dqs_p[4]}]

# PadFunction: IO_L3N_T0_DQS_AD1N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[4]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[4]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[4]}]
set_property PACKAGE_PIN N27 [get_ports {c0_ddr3_dqs_n[4]}]

# PadFunction: IO_L9P_T1_DQS_AD11P_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[5]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[5]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[5]}]
set_property PACKAGE_PIN U25 [get_ports {c0_ddr3_dqs_p[5]}]

# PadFunction: IO_L9N_T1_DQS_AD11N_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[5]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[5]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[5]}]
set_property PACKAGE_PIN U26 [get_ports {c0_ddr3_dqs_n[5]}]

# PadFunction: IO_L15P_T2_DQS_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[6]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[6]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[6]}]
set_property PACKAGE_PIN M30 [get_ports {c0_ddr3_dqs_p[6]}]

# PadFunction: IO_L15N_T2_DQS_ADV_B_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[6]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[6]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[6]}]
set_property PACKAGE_PIN M31 [get_ports {c0_ddr3_dqs_n[6]}]

# PadFunction: IO_L21P_T3_DQS_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_p[7]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_p[7]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_p[7]}]
set_property PACKAGE_PIN U32 [get_ports {c0_ddr3_dqs_p[7]}]

# PadFunction: IO_L21N_T3_DQS_A18_15 
set_property SLEW FAST [get_ports {c0_ddr3_dqs_n[7]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c0_ddr3_dqs_n[7]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_dqs_n[7]}]
set_property PACKAGE_PIN U33 [get_ports {c0_ddr3_dqs_n[7]}]

# PadFunction: IO_L3P_T0_DQS_16 
set_property SLEW FAST [get_ports {c0_ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_ck_p[0]}]
set_property PACKAGE_PIN B31 [get_ports {c0_ddr3_ck_p[0]}]

# PadFunction: IO_L3N_T0_DQS_16 
set_property SLEW FAST [get_ports {c0_ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c0_ddr3_ck_n[0]}]
set_property PACKAGE_PIN B32 [get_ports {c0_ddr3_ck_n[0]}]




set_property LOC PHASER_OUT_PHY_X0Y19 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y18 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y17 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y16 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y23 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y22 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y21 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y27 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y26 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y25 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y24 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]


set_property LOC PHASER_IN_PHY_X0Y19 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y18 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y17 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y16 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y23 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y22 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y21 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y27 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y26 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y25 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y24 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]





set_property LOC OUT_FIFO_X0Y19 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X0Y18 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X0Y17 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X0Y16 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property LOC OUT_FIFO_X0Y23 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X0Y22 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X0Y21 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X0Y27 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X0Y26 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X0Y25 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X0Y24 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]


set_property LOC IN_FIFO_X0Y19 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y18 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y17 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y16 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y27 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y26 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y25 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property LOC IN_FIFO_X0Y24 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]


set_property LOC PHY_CONTROL_X0Y4 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property LOC PHY_CONTROL_X0Y5 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property LOC PHY_CONTROL_X0Y6 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]


set_property LOC PHASER_REF_X0Y4 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property LOC PHASER_REF_X0Y5 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property LOC PHASER_REF_X0Y6 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]


set_property LOC OLOGIC_X0Y243 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y231 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y219 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y207 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y343 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y331 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y319 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property LOC OLOGIC_X0Y307 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]



set_property LOC PLLE2_ADV_X0Y5 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X0Y5 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
          


set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -setup 6

set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -hold 5

set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -setup 2 -start
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start

#set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_max_delay -to [get_pins -hier -include_replicated_objects -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1_reg[*]/D}] 20
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
#set_false_path -through [get_pins -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst}]
set_false_path -through [get_nets -hier -filter {NAME =~ */u_iodelay_ctrl/sys_rst_i}]
          
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
          
##################################################################################################
## Controller 1
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 8
## Time Period: 1875
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {c1_ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {c1_ddr3_ck_p[*]} ]
          
create_clock -period 1.875 [get_ports c1_sys_clk_p]
          
############## NET - IOSTANDARD ##################


# PadFunction: IO_L20P_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[0]}]
set_property PACKAGE_PIN C20 [get_ports {c1_ddr3_dq[0]}]

# PadFunction: IO_L20N_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[1]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[1]}]
set_property PACKAGE_PIN B20 [get_ports {c1_ddr3_dq[1]}]

# PadFunction: IO_L22P_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[2]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[2]}]
set_property PACKAGE_PIN B21 [get_ports {c1_ddr3_dq[2]}]

# PadFunction: IO_L22N_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[3]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[3]}]
set_property PACKAGE_PIN A21 [get_ports {c1_ddr3_dq[3]}]

# PadFunction: IO_L23P_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[4]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[4]}]
set_property PACKAGE_PIN B22 [get_ports {c1_ddr3_dq[4]}]

# PadFunction: IO_L23N_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[5]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[5]}]
set_property PACKAGE_PIN A23 [get_ports {c1_ddr3_dq[5]}]

# PadFunction: IO_L24P_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[6]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[6]}]
set_property PACKAGE_PIN C23 [get_ports {c1_ddr3_dq[6]}]

# PadFunction: IO_L24N_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dq[7]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dq[7]}]
set_property PACKAGE_PIN B23 [get_ports {c1_ddr3_dq[7]}]

# PadFunction: IO_L1P_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[13]}]
set_property PACKAGE_PIN H19 [get_ports {c1_ddr3_addr[13]}]

# PadFunction: IO_L1N_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[12]}]
set_property PACKAGE_PIN H20 [get_ports {c1_ddr3_addr[12]}]

# PadFunction: IO_L2P_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[11]}]
set_property PACKAGE_PIN H17 [get_ports {c1_ddr3_addr[11]}]

# PadFunction: IO_L2N_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[10]}]
set_property PACKAGE_PIN H18 [get_ports {c1_ddr3_addr[10]}]

# PadFunction: IO_L4P_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[9]}]
set_property PACKAGE_PIN F16 [get_ports {c1_ddr3_addr[9]}]

# PadFunction: IO_L4N_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[8]}]
set_property PACKAGE_PIN E16 [get_ports {c1_ddr3_addr[8]}]

# PadFunction: IO_L5P_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[7]}]
set_property PACKAGE_PIN E17 [get_ports {c1_ddr3_addr[7]}]

# PadFunction: IO_L5N_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[6]}]
set_property PACKAGE_PIN E18 [get_ports {c1_ddr3_addr[6]}]

# PadFunction: IO_L6P_T0_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[5]}]
set_property PACKAGE_PIN F18 [get_ports {c1_ddr3_addr[5]}]

# PadFunction: IO_L7P_T1_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[4]}]
set_property PACKAGE_PIN G20 [get_ports {c1_ddr3_addr[4]}]

# PadFunction: IO_L7N_T1_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[3]}]
set_property PACKAGE_PIN G21 [get_ports {c1_ddr3_addr[3]}]

# PadFunction: IO_L8P_T1_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[2]}]
set_property PACKAGE_PIN F20 [get_ports {c1_ddr3_addr[2]}]

# PadFunction: IO_L8N_T1_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[1]}]
set_property PACKAGE_PIN F21 [get_ports {c1_ddr3_addr[1]}]

# PadFunction: IO_L9P_T1_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_addr[0]}]
set_property PACKAGE_PIN G22 [get_ports {c1_ddr3_addr[0]}]

# PadFunction: IO_L9N_T1_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_ba[2]}]
set_property PACKAGE_PIN G23 [get_ports {c1_ddr3_ba[2]}]

# PadFunction: IO_L10P_T1_18 
set_property SLEW FAST [get_ports {c1_ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_ba[1]}]
set_property PACKAGE_PIN F23 [get_ports {c1_ddr3_ba[1]}]

# PadFunction: IO_L10N_T1_18 
set_property SLEW FAST [get_ports {c1_ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_ba[0]}]
set_property PACKAGE_PIN E23 [get_ports {c1_ddr3_ba[0]}]

# PadFunction: IO_L11P_T1_SRCC_18 
set_property SLEW FAST [get_ports {c1_ddr3_ras_n}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_ras_n}]
set_property PACKAGE_PIN D20 [get_ports {c1_ddr3_ras_n}]

# PadFunction: IO_L11N_T1_SRCC_18 
set_property SLEW FAST [get_ports {c1_ddr3_cas_n}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_cas_n}]
set_property PACKAGE_PIN D21 [get_ports {c1_ddr3_cas_n}]

# PadFunction: IO_L12P_T1_MRCC_18 
set_property SLEW FAST [get_ports {c1_ddr3_we_n}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_we_n}]
set_property PACKAGE_PIN E21 [get_ports {c1_ddr3_we_n}]

# PadFunction: IO_L13P_T2_MRCC_18 
set_property SLEW FAST [get_ports {c1_ddr3_reset_n}]
set_property IOSTANDARD LVCMOS15 [get_ports {c1_ddr3_reset_n}]
set_property PACKAGE_PIN E19 [get_ports {c1_ddr3_reset_n}]

# PadFunction: IO_L15P_T2_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_cke[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_cke[0]}]
set_property PACKAGE_PIN D16 [get_ports {c1_ddr3_cke[0]}]

# PadFunction: IO_L15N_T2_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_odt[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_odt[0]}]
set_property PACKAGE_PIN D17 [get_ports {c1_ddr3_odt[0]}]

# PadFunction: IO_L12N_T1_MRCC_18 
set_property SLEW FAST [get_ports {c1_ddr3_cs_n[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_cs_n[0]}]
set_property PACKAGE_PIN E22 [get_ports {c1_ddr3_cs_n[0]}]

# PadFunction: IO_L19P_T3_18 
set_property SLEW FAST [get_ports {c1_ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {c1_ddr3_dm[0]}]
set_property PACKAGE_PIN D22 [get_ports {c1_ddr3_dm[0]}]

# PadFunction: IO_L14P_T2_SRCC_18 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_sys_clk_p}]
set_property PACKAGE_PIN C18 [get_ports {c1_sys_clk_p}]

# PadFunction: IO_L14N_T2_SRCC_18 
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_sys_clk_n}]
set_property PACKAGE_PIN C19 [get_ports {c1_sys_clk_n}]

# PadFunction: IO_L21P_T3_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_dqs_p[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_ddr3_dqs_p[0]}]
set_property PACKAGE_PIN A19 [get_ports {c1_ddr3_dqs_p[0]}]

# PadFunction: IO_L21N_T3_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_dqs_n[0]}]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {c1_ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_ddr3_dqs_n[0]}]
set_property PACKAGE_PIN A20 [get_ports {c1_ddr3_dqs_n[0]}]

# PadFunction: IO_L3P_T0_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_ck_p[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_ddr3_ck_p[0]}]
set_property PACKAGE_PIN G17 [get_ports {c1_ddr3_ck_p[0]}]

# PadFunction: IO_L3N_T0_DQS_18 
set_property SLEW FAST [get_ports {c1_ddr3_ck_n[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {c1_ddr3_ck_n[0]}]
set_property PACKAGE_PIN G18 [get_ports {c1_ddr3_ck_n[0]}]




set_property LOC PHASER_OUT_PHY_X0Y31 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y30 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y29 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y28 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]


## set_property LOC PHASER_IN_PHY_X0Y31 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y30 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y29 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y28 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]





set_property LOC OUT_FIFO_X0Y31 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X0Y30 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property LOC OUT_FIFO_X0Y29 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property LOC OUT_FIFO_X0Y28 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]


set_property LOC IN_FIFO_X0Y28 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]


set_property LOC PHY_CONTROL_X0Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]


set_property LOC PHASER_REF_X0Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]


set_property LOC OLOGIC_X0Y357 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_std/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]



set_property LOC PLLE2_ADV_X0Y7 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X0Y7 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
          


