##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue May 26 19:54:42 2026

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.sd
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K480TIFFG1156_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         533.33000000000004 MHz
##                    Time Period:       1875 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->UDIMMs->MT8KTF51264AZ-1G4
## Data Width: 64
## Time Period: 1875
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {c0_ddr3_ck_p[*]} ]
          
create_clock -period 1.875 [get_ports c0_sys_clk_p]
          
create_clock -period 5 [get_ports clk_ref_p]
          
############## NET - IOSTANDARD ##################



##################################################################################################
## Controller 1
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 8
## Time Period: 1875
## Data Mask: 1
##################################################################################################

set_property IO_BUFFER_TYPE NONE [get_ports {c1_ddr3_ck_n[*]} ]
set_property IO_BUFFER_TYPE NONE [get_ports {c1_ddr3_ck_p[*]} ]
          
create_clock -period 1.875 [get_ports c1_sys_clk_p]
          
############## NET - IOSTANDARD ##################


